language: objective-c
xcode_project: TryingTravis.xcodeproj
xcode_scheme: TryingTravis

script:
  - xctool -sdk iphonesimulator -project TryingTravis.xcodeproj -scheme TryingTravis test  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  
  - git config --global user.name "V-FEXrt"
  - git config --global user.email "ashley78@ksu.edu"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${TOKEN}:@github.com" > .git/credentials
  - git status
  - git remote set-url origin https://github.com/V-FEXrt/TryingTravis.git
  - git pull origin master
  - git add --all
  - git commit -m "Committd by Travis-CI Updating Documentation for build $((TRAVIS_JOB_ID - 1))"
  - git status
  - git push origin master
  - git status
