language: objective-c
xcode_project: TryingTravis.xcodeproj
xcode_scheme: TryingTravis

script:
  - xctool -project TryingTravis.xcodeproj -scheme TryingTravis build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
