language: objective-c
xcode_project: TryingTravis.xcodeproj
xcode_scheme: TryingTravis

script:
  - xctool -sdk iphonesimulator -project TryingTravis.xcodeproj -scheme TryingTravis test  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  
  - git config --global user.name "V-FEXrt"
  - git config --global user.email "ashley78@ksu.edu"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${TOKEN}:@github.com" > .git/credentials
  - echo "HelloWorld" >> testfile.txt
  - git status
  - git add testfile.txt
  - git commit -m "Creating testfile"
  - git push origin master
